name: "Publish release"
on: [workflow_dispatch]

jobs:
  validation:
    name: Gradle Wrapper Validation
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: gradle/wrapper-validation-action@v1
  test:
    name: Test run
    needs: validation
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Setup Java
        uses: actions/setup-java@v1
        with:
          java-version: 8
      - name: Cache Gradle
        uses: actions/cache@v2
        env:
          java-version: 8
        with:
          path: |
            ~/.gradle/caches
            ~/.gradle/wrapper
          key: ${{ runner.os }}-${{ env.java-version }}-gradle-${{ hashFiles('**/*.gradle*') }}
          restore-keys: |
            ${{ runner.os }}-${{ env.java-version }}-gradle-
      - name: Make gradlew executable
        run: chmod +x ./gradlew
      - name: Gradle Check
        run: ./gradlew --info check
  build:
    name: Publish release
    needs: test
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Setup Java
        uses: actions/setup-java@v1
        with:
          java-version: 8
      - name: Cache Gradle
        uses: actions/cache@v2
        env:
          java-version: 8
        with:
          path: |
            ~/.gradle/caches
            ~/.gradle/wrapper
          key: ${{ runner.os }}-${{ env.java-version }}-gradle-${{ hashFiles('**/*.gradle*') }}
          restore-keys: |
            ${{ runner.os }}-${{ env.java-version }}-gradle-
      - name: Make gradlew executable
        run: chmod +x ./gradlew
      - name: Publish release
        env:
          BINTRAY_USER: ${{ secrets.BINTRAY_USER }}
          BINTRAY_PASS: ${{ secrets.BINTRAY_PASSWORD }}
        run: bash github-build.sh
#      - name: Commit release tag and next version
#        uses: stefanzweifel/git-auto-commit-action@v4
#        with:
#          push_options: '--follow-tags'
